FROM node:26.5-trixie-slim AS base

WORKDIR /app

FROM base AS vite

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/app/.npm \
    npm set cache /app/.npm && \
    npm ci

COPY . .

FROM vite AS dev

CMD ["npm", "run", "dev"]

EXPOSE 5173

FROM nginxinc/nginx-unprivileged:stable-trixie-perl as nginx

COPY --link --from=vite /app/nginx/nginx.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080