import type {
  OnlineDiffResponseDto,
  OnlineGameStateSnapshotResponse,
} from "../../../../src/api/ws/dto/gameplay/onlineGameplayProtocol";
import type { GameContent } from "../../../../src/game/rendering/ResourceManager";

export const testGameContent: GameContent = {
  version: "v1.0",
  world: {
    biomes: ["forest", "desert", "ice"],
    width: 2400,
    height: 768,
    tickRateHz: 30,
    gravity: 260,
    projectileTimeStepSeconds: 0.03333333333333333,
    maxProjectileSteps: 400,
    movementSegmentDurationTicks: 3,
    playerASpawnRegion: { minX: 240, maxX: 800 },
    playerBSpawnRegion: { minX: 1600, maxX: 2160 },
    minWind: -50,
    maxWind: 50,
    turnDurationSeconds: 30,
    matchDurationSeconds: 180,
    postImpactDelaySeconds: 0.55,
    lootCrates: {
      hpValue: 25,
      fuelValue: 50,
      ammoValue: 1,
      collectionRadius: 35,
      dropSpeed: 150,
      spawnScheduleSeconds: [120, 60, 30],
      spawnEdgeMargin: 100,
      maxActiveCrates: 3,
    },
  },
  projectiles: {
    standardKaboom: {
      id: "standardKaboom",
      name: "Standard Kaboom",
      label: "SK",
      isDefault: true,
      radius: 4.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: -1,
      terrainEffectType: "CRATER",
      terrainRadius: 42,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 42,
      damage: 45,
      subMunitions: null,
      damageTrail: null,
    },
    magmaMortar: {
      id: "magmaMortar",
      name: "Magma Mortar",
      label: "MM",
      isDefault: false,
      radius: 6.0,
      baseVelocity: 1.05,
      gravityScale: 1.0,
      initialAmmo: 2,
      terrainEffectType: "CRATER",
      terrainRadius: 55,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 55,
      damage: 60,
      subMunitions: null,
      damageTrail: null,
    },
    dragonsBreath: {
      id: "dragonsBreath",
      name: "Dragon's Breath",
      label: "DB",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 28,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 28,
      damage: 25,
      subMunitions: null,
      damageTrail: {
        radius: 50.0,
        damagePerSecond: 12.0,
        durationSeconds: 5.0,
        hazardType: "FIRE",
      },
    },
    lavaHopper: {
      id: "lavaHopper",
      name: "Lava Hopper",
      label: "LH",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 32,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 32,
      damage: 18,
      subMunitions: null,
      damageTrail: null,
      bouncer: {
        bounceCount: 4,
        durationSeconds: 4.0,
        damagePerBounce: 18.0,
        shockwaveRadius: 32.0,
      },
    },
    pyroclastCataclysm: {
      id: "pyroclastCataclysm",
      name: "Pyroclast Cataclysm",
      label: "PC",
      isDefault: false,
      radius: 9.0,
      baseVelocity: 1.15,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 85,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 85,
      damage: 85,
      subMunitions: null,
      damageTrail: null,
    },
    cryoNeedle: {
      id: "cryoNeedle",
      name: "Cryo Needle",
      label: "CN",
      isDefault: false,
      radius: 3.0,
      baseVelocity: 1.45,
      gravityScale: 0.35,
      initialAmmo: 2,
      terrainEffectType: "DRILL",
      terrainRadius: 22,
      terrainDepth: 65,
      damageEffectType: "FOCUSED",
      damageRadius: 25,
      damage: 65,
      subMunitions: null,
      damageTrail: null,
    },
    apexAvalanche: {
      id: "apexAvalanche",
      name: "Apex Avalanche",
      label: "AA",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 18,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 18,
      damage: 20,
      subMunitions: null,
      damageTrail: null,
      apexSplit: {
        splitCount: 6,
        totalDamagePool: 65.0,
        spreadVelocity: 120.0,
      },
    },
    frostbiteZone: {
      id: "frostbiteZone",
      name: "Frostbite Zone",
      label: "FZ",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 25,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 25,
      damage: 20,
      subMunitions: null,
      damageTrail: {
        radius: 52.0,
        damagePerSecond: 10.0,
        durationSeconds: 5.0,
        hazardType: "FROST",
      },
    },
    glacialShatter: {
      id: "glacialShatter",
      name: "Glacial Shatter",
      label: "GS",
      isDefault: false,
      radius: 8.0,
      baseVelocity: 1.15,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 65,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 65,
      damage: 75,
      subMunitions: null,
      damageTrail: null,
    },
    gravelGatling: {
      id: "gravelGatling",
      name: "Gravel Gatling",
      label: "GG",
      isDefault: false,
      radius: 3.5,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 2,
      terrainEffectType: "CRATER",
      terrainRadius: 22,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 22,
      damage: 22,
      subMunitions: null,
      damageTrail: null,
      salvo: {
        shotCount: 3,
        delaySeconds: 0.1,
        gravityScales: [0.92, 1.0, 1.08],
      },
    },
    tectonicThumper: {
      id: "tectonicThumper",
      name: "Tectonic Thumper",
      label: "TT",
      isDefault: false,
      radius: 6.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 35,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 35,
      damage: 20,
      subMunitions: null,
      damageTrail: null,
      bouncer: {
        bounceCount: 4,
        durationSeconds: 4.0,
        damagePerBounce: 20.0,
        shockwaveRadius: 36.0,
      },
    },
    sinkholeDrill: {
      id: "sinkholeDrill",
      name: "Sinkhole Drill",
      label: "SD",
      isDefault: false,
      radius: 6.0,
      baseVelocity: 1.25,
      gravityScale: 0.8,
      initialAmmo: 1,
      terrainEffectType: "DRILL",
      terrainRadius: 36,
      terrainDepth: 80,
      damageEffectType: "FOCUSED",
      damageRadius: 36,
      damage: 55,
      subMunitions: null,
      damageTrail: null,
    },
    quakeFissure: {
      id: "quakeFissure",
      name: "Quake Fissure",
      label: "QF",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 26,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 26,
      damage: 20,
      subMunitions: null,
      damageTrail: {
        radius: 48.0,
        damagePerSecond: 10.0,
        durationSeconds: 5.0,
        hazardType: "QUAKE",
      },
    },
    arcSalvo: {
      id: "arcSalvo",
      name: "Arc Salvo",
      label: "AS",
      isDefault: false,
      radius: 3.5,
      baseVelocity: 1.05,
      gravityScale: 1.0,
      initialAmmo: 2,
      terrainEffectType: "CRATER",
      terrainRadius: 20,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 20,
      damage: 20,
      subMunitions: null,
      damageTrail: null,
      salvo: {
        shotCount: 3,
        delaySeconds: 0.1,
        gravityScales: [0.85, 1.0, 1.15],
      },
    },
    staticApexStar: {
      id: "staticApexStar",
      name: "Static Apex Star",
      label: "SS",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 20,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 20,
      damage: 20,
      subMunitions: null,
      damageTrail: null,
      apexSplit: {
        splitCount: 6,
        totalDamagePool: 65.0,
        spreadVelocity: 130.0,
      },
    },
    teslaGrid: {
      id: "teslaGrid",
      name: "Tesla Grid",
      label: "TG",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.0,
      gravityScale: 1.0,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 25,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 25,
      damage: 15,
      subMunitions: null,
      damageTrail: {
        radius: 50.0,
        damagePerSecond: 12.0,
        durationSeconds: 5.0,
        hazardType: "ELECTRIC",
      },
    },
    thunderstrikeCore: {
      id: "thunderstrikeCore",
      name: "Thunderstrike Core",
      label: "TC",
      isDefault: false,
      radius: 5.0,
      baseVelocity: 1.6,
      gravityScale: 0.25,
      initialAmmo: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 45,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 45,
      damage: 80,
      subMunitions: null,
      damageTrail: null,
    },
  },
  tanks: {
    ignis: {
      id: "ignis",
      name: "Ignis",
      maxHealth: 100,
      maxFuel: 240,
      movementQuantum: 24,
      fuelRate: 1,
      climbCapability: 5,
      width: 44,
      height: 28,
      barrelLength: 28.0,
      turretYOffset: -14.0,
      visual: {
        fill: "#ef4444",
        stroke: "#991b1b",
        accent: "#facc15",
        label: "IG",
      },
      loadout: [
        "standardKaboom",
        "magmaMortar",
        "dragonsBreath",
        "lavaHopper",
        "pyroclastCataclysm",
      ],
    },
    glacies: {
      id: "glacies",
      name: "Glacies",
      maxHealth: 100,
      maxFuel: 240,
      movementQuantum: 24,
      fuelRate: 1,
      climbCapability: 5,
      width: 44,
      height: 28,
      barrelLength: 28.0,
      turretYOffset: -14.0,
      visual: {
        fill: "#38bdf8",
        stroke: "#0284c7",
        accent: "#e0f2fe",
        label: "GL",
      },
      loadout: [
        "standardKaboom",
        "cryoNeedle",
        "apexAvalanche",
        "frostbiteZone",
        "glacialShatter",
      ],
    },
    terra: {
      id: "terra",
      name: "Terra",
      maxHealth: 100,
      maxFuel: 240,
      movementQuantum: 24,
      fuelRate: 1,
      climbCapability: 5,
      width: 44,
      height: 28,
      barrelLength: 28.0,
      turretYOffset: -14.0,
      visual: {
        fill: "#d97706",
        stroke: "#78350f",
        accent: "#fde68a",
        label: "TR",
      },
      loadout: [
        "standardKaboom",
        "gravelGatling",
        "tectonicThumper",
        "sinkholeDrill",
        "quakeFissure",
      ],
    },
    volt: {
      id: "volt",
      name: "Volt",
      maxHealth: 100,
      maxFuel: 240,
      movementQuantum: 24,
      fuelRate: 1,
      climbCapability: 5,
      width: 44,
      height: 28,
      barrelLength: 28.0,
      turretYOffset: -14.0,
      visual: {
        fill: "#a855f7",
        stroke: "#581c87",
        accent: "#06b6d4",
        label: "VT",
      },
      loadout: [
        "standardKaboom",
        "arcSalvo",
        "staticApexStar",
        "teslaGrid",
        "thunderstrikeCore",
      ],
    },
  },
};

export function createTestSnapshot(): OnlineGameStateSnapshotResponse {
  return {
    gameContentVersion: "v1.0",
    gameContent: {
      version: testGameContent.version,
      world: {
        biomes: testGameContent.world.biomes,
        width: testGameContent.world.width,
        height: testGameContent.world.height,
        tickRateHz: testGameContent.world.tickRateHz,
        gravity: testGameContent.world.gravity,
        deltaTime: testGameContent.world.projectileTimeStepSeconds,
        maxProjectileSteps: testGameContent.world.maxProjectileSteps,
        movementSegmentDurationTicks: testGameContent.world.movementSegmentDurationTicks,
        playerASpawnRegion: { minX: 240, maxX: 800 },
        playerBSpawnRegion: { minX: 1600, maxX: 2160 },
        minWind: testGameContent.world.minWind,
        maxWind: testGameContent.world.maxWind,
        turnDurationSeconds: testGameContent.world.turnDurationSeconds,
        matchDurationSeconds: testGameContent.world.matchDurationSeconds,
        postImpactDelaySeconds: testGameContent.world.postImpactDelaySeconds,
        lootCrates: testGameContent.world.lootCrates,
      },
      tanks: Object.fromEntries(
        Object.entries(testGameContent.tanks).map(([id, tank]) => [
          id,
          {
            id: tank.id,
            name: tank.name,
            maxHealth: tank.maxHealth,
            maxFuel: tank.maxFuel,
            movementQuantum: tank.movementQuantum,
            fuelRate: tank.fuelRate,
            climbCapability: tank.climbCapability,
            width: tank.width,
            height: tank.height,
            barrelLength: tank.barrelLength,
            turretYOffset: tank.turretYOffset,
            visual: {
              fillStyle: tank.visual.fill,
              strokeStyle: tank.visual.stroke,
              accentColor: tank.visual.accent,
              label: tank.visual.label,
            },
            loadout: tank.loadout,
          },
        ]),
      ),
      projectiles: Object.fromEntries(
        Object.entries(testGameContent.projectiles).map(([id, proj]) => [
          id,
          {
            id: proj.id,
            name: proj.name,
            label: proj.label,
            isDefault: proj.isDefault,
            radius: proj.radius,
            baseVelocity: proj.baseVelocity,
            gravityScale: proj.gravityScale,
            terrainEffectType: proj.terrainEffectType,
            terrainRadius: proj.terrainRadius,
            terrainDepth: proj.terrainDepth,
            damageEffectType: proj.damageEffectType,
            damageRadius: proj.damageRadius,
            damage: proj.damage,
            subMunitions: proj.subMunitions,
            damageTrail: proj.damageTrail,
          },
        ]),
      ),
    },
    match: {
      phase: "AIMING",
      activePlayerId: 1,
      playerCount: 2,
      turnNumber: 1,
      turnTimeRemainingTicks: 900,
      winnerPlayerId: null,
      matchTimeRemainingTicks: 5400,
      wind: 0,
      biome: "forest",
    },
    terrain: {
      kind: "HEIGHTMAP",
      width: 2400,
      height: 768,
      surface: new Array(2400).fill(400),
    },
    tanks: [
      {
        entityId: 10,
        playerId: 1,
        displayName: "Player 1",
        tankDefinitionId: "ignis",
        width: 44,
        height: 28,
        visual: { fillStyle: "#ef4444", strokeStyle: "#991b1b", accentColor: "#facc15", label: "IG" },
        position: { x: 200, y: 386 },
        facing: 1,
        aimAngle: -Math.PI / 4,
        power: 300,
        selectedProjectileSlotId: "standardKaboom",
        loadout: [...testGameContent.tanks["ignis"]!.loadout],
        health: 100,
        maxHealth: 100,
        fuel: 240,
        maxFuel: 240,
        alive: true,
      },
      {
        entityId: 20,
        playerId: 2,
        displayName: "Player 2",
        tankDefinitionId: "glacies",
        width: 44,
        height: 28,
        visual: { fillStyle: "#38bdf8", strokeStyle: "#0284c7", accentColor: "#bae6fd", label: "GL" },
        position: { x: 1800, y: 386 },
        facing: -1,
        aimAngle: -Math.PI / 4,
        power: 300,
        selectedProjectileSlotId: "standardKaboom",
        loadout: [...testGameContent.tanks["glacies"]!.loadout],
        health: 100,
        maxHealth: 100,
        fuel: 240,
        maxFuel: 240,
        alive: true,
      },
    ],
    projectiles: [],
    lootCrates: [],
    damageTrails: [],
  };
}

export function createInitialDiff(sequence: number): OnlineDiffResponseDto {
  return {
    gameSessionId: "test-session-123",
    sequence,
    serverTick: sequence * 10,
    type: "INITIAL_STATE",
    intentId: null,
    payload: {
      expectedNextDiffSequence: sequence + 1,
      localPlayerId: 1,
      state: createTestSnapshot(),
    },
  };
}
