import type {
  OnlineDiffResponseDto,
  OnlineGameStateSnapshotResponse,
} from "../../../../src/api/ws/dto/gameplay/onlineGameplayProtocol";
import type { GameContent } from "../../../../src/game/rendering/ResourceManager";

export const testGameContent: GameContent = {
  version: "v1.0",
  world: {
    biome: "forest",
    width: 2400,
    height: 768,
    tickRateHz: 30,
    gravity: 260,
    projectileTimeStepSeconds: 0.05,
    maxProjectileSteps: 400,
    movementSegmentDurationTicks: 15,
    minWind: -50,
    maxWind: 50,
  },
  projectiles: {
    basicShell: {
      id: "basicShell",
      name: "Basic Shell",
      label: "BS",
      radius: 4,
      baseVelocity: 1,
      gravityScale: 0,
      drag: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 46,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 46,
      damage: 48,
      subMunitions: null,
      damageTrail: null,
    },
    titanShell: {
      id: "titanShell",
      name: "Titan Shell",
      label: "TS",
      radius: 9,
      baseVelocity: 1.25,
      gravityScale: 0.015,
      drag: 0.88,
      terrainEffectType: "CRATER",
      terrainRadius: 85,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 85,
      damage: 85,
      subMunitions: null,
      damageTrail: null,
    },
    cluster: {
      id: "cluster",
      name: "Cluster",
      label: "C",
      radius: 3,
      baseVelocity: 0.92,
      gravityScale: 0.035,
      drag: 1.12,
      terrainEffectType: "CRATER",
      terrainRadius: 30,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 78,
      damage: 30,
      subMunitions: {
        count: 3,
        projectileDefinitionId: "basicShell",
        spreadAngleDegrees: 30,
        velocityScale: 0.5,
      },
      damageTrail: null,
    },
    heavyShell: {
      id: "heavyShell",
      name: "Cyber Laser",
      label: "CL",
      radius: 7,
      baseVelocity: 1.14,
      gravityScale: 0.01,
      drag: 0.92,
      terrainEffectType: "DRILL",
      terrainRadius: 38,
      terrainDepth: 42,
      damageEffectType: "FOCUSED",
      damageRadius: 34,
      damage: 72,
      subMunitions: null,
      damageTrail: null,
    },
    thermalHazard: {
      id: "thermalHazard",
      name: "Thermal Hazard",
      label: "TH",
      radius: 5,
      baseVelocity: 1,
      gravityScale: 0,
      drag: 1,
      terrainEffectType: "CRATER",
      terrainRadius: 25,
      terrainDepth: 0,
      damageEffectType: "RADIAL",
      damageRadius: 45,
      damage: 15,
      subMunitions: null,
      damageTrail: {
        radius: 45,
        damagePerSecond: 10,
        durationSeconds: 5,
      },
    },
  },
  tanks: {
    "vanguard-cyber": {
      id: "vanguard-cyber",
      name: "Vanguard Cyber",
      maxHealth: 100,
      maxFuel: 240,
      movementQuantum: 8,
      fuelRate: 1,
      climbCapability: 5,
      width: 24,
      height: 24,
      visual: {
        fill: "#3b82f6",
        stroke: "#1d4ed8",
        accent: "#60a5fa",
        label: "VC",
      },
      loadout: ["basicShell", "cluster", "heavyShell"],
    },
    "heavy-armor": {
      id: "heavy-armor",
      name: "Heavy Armor",
      maxHealth: 100,
      maxFuel: 180,
      movementQuantum: 8,
      fuelRate: 1,
      climbCapability: 5,
      width: 24,
      height: 24,
      visual: {
        fill: "#ef4444",
        stroke: "#b91c1c",
        accent: "#f87171",
        label: "HA",
      },
      loadout: ["basicShell", "titanShell"],
    },
    "desert-striker": {
      id: "desert-striker",
      name: "Desert Striker",
      maxHealth: 100,
      maxFuel: 280,
      movementQuantum: 8,
      fuelRate: 1,
      climbCapability: 5,
      width: 24,
      height: 24,
      visual: {
        fill: "#f59e0b",
        stroke: "#b45309",
        accent: "#fbbf24",
        label: "DS",
      },
      loadout: ["basicShell", "thermalHazard"],
    },
    specter: {
      id: "specter",
      name: "Specter",
      maxHealth: 100,
      maxFuel: 240,
      movementQuantum: 8,
      fuelRate: 1,
      climbCapability: 5,
      width: 24,
      height: 24,
      visual: {
        fill: "#8b5cf6",
        stroke: "#6d28d9",
        accent: "#a78bfa",
        label: "S",
      },
      loadout: ["basicShell"],
    },
  },
};

export function createTestSnapshot(): OnlineGameStateSnapshotResponse {
  return {
    gameContentVersion: "v1.0",
    gameContent: {
      version: testGameContent.version,
      world: {
        biome: testGameContent.world.biome,
        width: testGameContent.world.width,
        height: testGameContent.world.height,
        tickRateHz: testGameContent.world.tickRateHz,
        gravity: testGameContent.world.gravity,
        deltaTime: testGameContent.world.projectileTimeStepSeconds,
        maxProjectileSteps: testGameContent.world.maxProjectileSteps,
        movementSegmentDurationTicks: testGameContent.world.movementSegmentDurationTicks,
        playerASpawnRegion: { minX: 240, maxX: 800 },
        playerBSpawnRegion: { minX: 1600, maxX: 2160 },
        minWind: testGameContent.world.minWind,
        maxWind: testGameContent.world.maxWind,
      },
      tanks: Object.fromEntries(
        Object.entries(testGameContent.tanks).map(([id, tank]) => [
          id,
          {
            id: tank.id,
            name: tank.name,
            maxHealth: tank.maxHealth,
            maxFuel: tank.maxFuel,
            movementQuantum: tank.movementQuantum,
            fuelRate: tank.fuelRate,
            climbCapability: tank.climbCapability,
            width: tank.width,
            height: tank.height,
            visual: {
              fillStyle: tank.visual.fill,
              strokeStyle: tank.visual.stroke,
              accentColor: tank.visual.accent,
              label: tank.visual.label,
            },
            loadout: tank.loadout,
          },
        ]),
      ),
      projectiles: Object.fromEntries(
        Object.entries(testGameContent.projectiles).map(([id, proj]) => [
          id,
          {
            id: proj.id,
            name: proj.name,
            label: proj.label,
            radius: proj.radius,
            baseVelocity: proj.baseVelocity,
            gravityScale: proj.gravityScale,
            drag: proj.drag,
            terrainEffectType: proj.terrainEffectType,
            terrainRadius: proj.terrainRadius,
            terrainDepth: proj.terrainDepth,
            damageEffectType: proj.damageEffectType,
            damageRadius: proj.damageRadius,
            damage: proj.damage,
            subMunitions: proj.subMunitions,
            damageTrail: proj.damageTrail,
          },
        ]),
      ),
    },
    match: {
      phase: "AIMING",
      activePlayerId: 1,
      playerCount: 2,
      turnNumber: 1,
      turnTimeRemainingTicks: 900,
      winnerPlayerId: null,
      matchTimeRemainingTicks: 5400,
      wind: 0,
      biome: "forest",
    },
    terrain: {
      kind: "HEIGHTMAP",
      width: 2400,
      height: 768,
      surface: new Array(2400).fill(400),
    },
    tanks: [
      {
        entityId: 10,
        playerId: 1,
        displayName: "Player 1",
        tankDefinitionId: "vanguard-cyber",
        width: 24,
        height: 24,
        visual: { fillStyle: "#3b82f6", strokeStyle: "#1d4ed8", accentColor: "#60a5fa", label: "P1" },
        position: { x: 200, y: 388 },
        facing: 1,
        aimAngle: -Math.PI / 4,
        power: 300,
        selectedProjectileSlotId: "basicShell",
        loadout: ["basicShell"],
        health: 100,
        maxHealth: 100,
        fuel: 240,
        alive: true,
      },
      {
        entityId: 20,
        playerId: 2,
        displayName: "Player 2",
        tankDefinitionId: "vanguard-cyber",
        width: 24,
        height: 24,
        visual: { fillStyle: "#ef4444", strokeStyle: "#b91c1c", accentColor: "#f87171", label: "P2" },
        position: { x: 1800, y: 388 },
        facing: -1,
        aimAngle: -Math.PI / 4,
        power: 300,
        selectedProjectileSlotId: "basicShell",
        loadout: ["basicShell"],
        health: 100,
        maxHealth: 100,
        fuel: 240,
        alive: true,
      },
    ],
    projectiles: [],
    lootCrates: [],
    damageTrails: [],
  };
}

export function createInitialDiff(sequence = 1): OnlineDiffResponseDto {
  return {
    gameSessionId: "test-session-123",
    sequence,
    serverTick: sequence * 10,
    type: "INITIAL_STATE",
    intentId: null,
    payload: {
      expectedNextDiffSequence: sequence + 1,
      localPlayerId: 1,
      state: createTestSnapshot(),
    },
  };
}
