spring.application.name=server
logging.level.org.springframework.security=DEBUG

app.jwt.secret=c7ahg6EGg/dRAs9K/kNmmr3jsT5ltEtd+vQbUVh4YOVvt9wfVmnr94pY7hYbnJBg+2aN0FJpZPB0WLoaYFewuw==
# 1 hour
app.jwt.access-token-expiration-ms=3600000
# 1 week
app.jwt.refresh-token-expiration-ms=604800000


##############################
#          DATABASE          #
##############################

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/prod
spring.datasource.username=david
spring.datasource.password=david

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/schema.sql
spring.sql.init.data-locations=classpath:/data.sql
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
