spring.application.name=server
logging.level.org.springframework.security=INFO
spring.profiles.active=local,dev

# 1 hour
app.jwt.access-token-expiration-ms=3600000
# 1 week
app.jwt.refresh-token-expiration-ms=604800000

##############################
#          POSTGRES          #
##############################

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/prod
spring.datasource.username=david
spring.datasource.password=david


spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

###########################
#          redis          #
###########################

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0

spring.mvc.problemdetails.enabled=true