import type { ProjectileDefinition, TankDefinition } from "../types";

export type GameContent = {
  version: string;
  world: {
    width: number;
    height: number;
    bedrockDepth: number;
    tickRateHz: number;
    gravity: number;
    projectileTimeStepSeconds: number;
    maxProjectileSteps: number;
    movementSegmentDurationTicks: number;
  };
  tanks: Record<string, TankDefinition>;
  projectiles: Record<string, ProjectileDefinition>;
};

export const mockGameContent: GameContent = {
  version: "game-content.v1",
  world: {
    width: 1280,
    height: 720,
    bedrockDepth: 40,
    tickRateHz: 30,
    gravity: 500,
    projectileTimeStepSeconds: 1 / 30,
    maxProjectileSteps: 180,
    movementSegmentDurationTicks: 6,
  },
  projectiles: {
    basicShell: {
      id: "basicShell",
      name: "Basic Shell",
      physics: {
        radius: 4,
        gravityScale: 1,
        drag: 0,
        muzzleVelocityScale: 1,
      },
      terrainEffect: { type: "crater", radius: 46 },
      damageEffect: { type: "radial", radius: 46, damage: 48 },
      impactAnimationId: "orange-pop",
      impactDuration: 0.42,
      visual: {
        fill: "#f8fafc",
        stroke: "#f97316",
        accent: "#fed7aa",
        label: "S",
      },
    },
    mortar: {
      id: "mortar",
      name: "Mortar",
      physics: {
        radius: 5,
        gravityScale: 1.36,
        drag: 0.02,
        muzzleVelocityScale: 0.78,
      },
      terrainEffect: { type: "crater", radius: 64 },
      damageEffect: { type: "radial", radius: 62, damage: 38 },
      impactAnimationId: "smoke-ring",
      impactDuration: 0.58,
      visual: {
        fill: "#a7f3d0",
        stroke: "#10b981",
        accent: "#064e3b",
        label: "M",
      },
    },
    heavyShell: {
      id: "heavyShell",
      name: "Heavy Shell",
      physics: {
        radius: 7,
        gravityScale: 1.14,
        drag: 0.01,
        muzzleVelocityScale: 0.92,
      },
      terrainEffect: { type: "drill", radius: 38, depth: 42 },
      damageEffect: { type: "focused", radius: 34, damage: 72 },
      impactAnimationId: "red-slam",
      impactDuration: 0.5,
      visual: {
        fill: "#fecaca",
        stroke: "#ef4444",
        accent: "#7f1d1d",
        label: "H",
      },
    },
    cluster: {
      id: "cluster",
      name: "Cluster",
      physics: {
        radius: 3,
        gravityScale: 0.92,
        drag: 0.035,
        muzzleVelocityScale: 1.12,
      },
      terrainEffect: { type: "crater", radius: 30 },
      damageEffect: { type: "radial", radius: 78, damage: 30 },
      impactAnimationId: "spark-burst",
      impactDuration: 0.48,
      visual: {
        fill: "#fde68a",
        stroke: "#eab308",
        accent: "#713f12",
        label: "C",
      },
    },
    needle: {
      id: "needle",
      name: "Needle",
      physics: {
        radius: 2,
        gravityScale: 0.8,
        drag: 0,
        muzzleVelocityScale: 1.35,
      },
      terrainEffect: { type: "drill", radius: 16, depth: 56 },
      damageEffect: { type: "focused", radius: 22, damage: 58 },
      impactAnimationId: "blue-flash",
      impactDuration: 0.36,
      visual: {
        fill: "#bfdbfe",
        stroke: "#3b82f6",
        accent: "#1e3a8a",
        label: "N",
      },
    },
    // Heavy Armor signature projectile
    titanShell: {
      id: "titanShell",
      name: "Titan Shell",
      physics: {
        radius: 9,
        gravityScale: 1.25,
        drag: 0.015,
        muzzleVelocityScale: 0.88,
      },
      terrainEffect: { type: "crater", radius: 80 },
      damageEffect: { type: "radial", radius: 75, damage: 85 },
      impactAnimationId: "red-slam",
      impactDuration: 0.65,
      visual: {
        fill: "#ef4444",
        stroke: "#991b1b",
        accent: "#fca5a5",
        label: "T",
      },
    },
    // Desert Striker signature projectile
    precisionDart: {
      id: "precisionDart",
      name: "Precision Dart",
      physics: {
        radius: 3,
        gravityScale: 0.65,
        drag: 0.005,
        muzzleVelocityScale: 1.45,
      },
      terrainEffect: { type: "drill", radius: 20, depth: 70 },
      damageEffect: { type: "focused", radius: 25, damage: 65 },
      impactAnimationId: "spark-burst",
      impactDuration: 0.4,
      visual: {
        fill: "#f59e0b",
        stroke: "#b45309",
        accent: "#fef08a",
        label: "P",
      },
    },
    // Vanguard Cyber signature projectile
    pulseRail: {
      id: "pulseRail",
      name: "Pulse Rail",
      physics: {
        radius: 5,
        gravityScale: 0.75,
        drag: 0,
        muzzleVelocityScale: 1.3,
      },
      terrainEffect: { type: "crater", radius: 52 },
      damageEffect: { type: "radial", radius: 50, damage: 60 },
      impactAnimationId: "blue-flash",
      impactDuration: 0.45,
      visual: {
        fill: "#38bdf8",
        stroke: "#0284c7",
        accent: "#e0f2fe",
        label: "R",
      },
    },
  },
  tanks: {
    "heavy-armor": {
      id: "heavy-armor",
      name: "Heavy Armor",
      maxHealth: 130,
      maxFuel: 180,
      movementQuantum: 6,
      fuelRate: 1.2,
      climbCapability: 4,
      collisionRadius: 36,
      halfWidth: 18,
      trackGroundOffset: 0,
      muzzleForwardOffset: 20,
      muzzleVerticalOffset: 24,
      visual: {
        fill: "#4b5563",
        stroke: "#1f2937",
        accent: "#9ca3af",
        label: "H",
      },
      loadout: [
        { id: "titan", projectileDefinitionId: "titanShell", label: "Ttn" },
        { id: "heavy", projectileDefinitionId: "heavyShell", label: "Hvy" },
        { id: "mortar", projectileDefinitionId: "mortar", label: "Mtr" },
        { id: "standard", projectileDefinitionId: "basicShell", label: "Std" },
        { id: "cluster", projectileDefinitionId: "cluster", label: "Clu" },
      ],
    },
    "desert-striker": {
      id: "desert-striker",
      name: "Desert Striker",
      maxHealth: 95,
      maxFuel: 280,
      movementQuantum: 10,
      fuelRate: 0.8,
      climbCapability: 6,
      collisionRadius: 30,
      halfWidth: 15,
      trackGroundOffset: 0,
      muzzleForwardOffset: 22,
      muzzleVerticalOffset: 22,
      visual: {
        fill: "#d97706",
        stroke: "#78350f",
        accent: "#fde68a",
        label: "D",
      },
      loadout: [
        { id: "precision", projectileDefinitionId: "precisionDart", label: "Prc" },
        { id: "needle", projectileDefinitionId: "needle", label: "Ndl" },
        { id: "cluster", projectileDefinitionId: "cluster", label: "Clu" },
        { id: "standard", projectileDefinitionId: "basicShell", label: "Std" },
        { id: "mortar", projectileDefinitionId: "mortar", label: "Mtr" },
      ],
    },
    "vanguard-cyber": {
      id: "vanguard-cyber",
      name: "Vanguard Cyber",
      maxHealth: 110,
      maxFuel: 240,
      movementQuantum: 8,
      fuelRate: 1,
      climbCapability: 5,
      collisionRadius: 32,
      halfWidth: 16,
      trackGroundOffset: 0,
      muzzleForwardOffset: 18,
      muzzleVerticalOffset: 24,
      visual: {
        fill: "#0284c7",
        stroke: "#0c4a6e",
        accent: "#7dd3fc",
        label: "V",
      },
      loadout: [
        { id: "rail", projectileDefinitionId: "pulseRail", label: "Rail" },
        { id: "needle", projectileDefinitionId: "needle", label: "Ndl" },
        { id: "heavy", projectileDefinitionId: "heavyShell", label: "Hvy" },
        { id: "standard", projectileDefinitionId: "basicShell", label: "Std" },
        { id: "cluster", projectileDefinitionId: "cluster", label: "Clu" },
      ],
    },
    vanguard: {
      id: "vanguard",
      name: "Vanguard",
      maxHealth: 110,
      maxFuel: 240,
      movementQuantum: 8,
      fuelRate: 1,
      climbCapability: 5,
      collisionRadius: 32,
      halfWidth: 16,
      trackGroundOffset: 0,
      muzzleForwardOffset: 18,
      muzzleVerticalOffset: 24,
      visual: {
        fill: "#22c55e",
        stroke: "#14532d",
        accent: "#bbf7d0",
        label: "V",
      },
      loadout: [
        { id: "standard", projectileDefinitionId: "basicShell", label: "Std" },
        { id: "mortar", projectileDefinitionId: "mortar", label: "Mtr" },
        { id: "heavy", projectileDefinitionId: "heavyShell", label: "Hvy" },
        { id: "cluster", projectileDefinitionId: "cluster", label: "Clu" },
        { id: "needle", projectileDefinitionId: "needle", label: "Ndl" },
      ],
    },
    specter: {
      id: "specter",
      name: "Specter",
      maxHealth: 94,
      maxFuel: 240,
      movementQuantum: 8,
      fuelRate: 1,
      climbCapability: 5,
      collisionRadius: 32,
      halfWidth: 16,
      trackGroundOffset: 0,
      muzzleForwardOffset: 18,
      muzzleVerticalOffset: 24,
      visual: {
        fill: "#60a5fa",
        stroke: "#1e3a8a",
        accent: "#dbeafe",
        label: "S",
      },
      loadout: [
        { id: "standard", projectileDefinitionId: "basicShell", label: "Std" },
        { id: "mortar", projectileDefinitionId: "mortar", label: "Mtr" },
        { id: "heavy", projectileDefinitionId: "heavyShell", label: "Hvy" },
        { id: "cluster", projectileDefinitionId: "cluster", label: "Clu" },
        { id: "needle", projectileDefinitionId: "needle", label: "Ndl" },
      ],
    },
  },
};
