name: tanks

services:
  postgres:
    image: postgres:18-alpine3.23
    restart: always
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: david
      POSTGRES_DB: prod
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  pgdata: